-- INSERT INTO mng_user ('id', 'USER_NAME', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'ROLE', 'SSN') VALUES (101, 'rafsa@gmail.com', 'Rafael', 'Rafa', 'admin', 'ssn101');
-- INSERT INTO mng_user VALUES (102, 'rafa2@gmail.com', 'Rafael2', 'Rafa', 'admin', 'ssn1012');
-- INSERT INTO mng_user VALUES (103, 'rafa3@gmail.com', 'Rafael3', 'Rafa', 'admin', 'ssn103');
-- INSERT INTO mng_user VALUES (104, 'rafa4@gmail.com', 'Rafael3', 'Rafa', 'admin', 'ssn104');