version: '3'

services:
  redis-app:
    image: redis:5.0.5
    ports:
      - "6379:6379"
    volumes:
      - .docker/redisdata:/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge